<?xml version="1.0" standalone="no" ?>
<!--
######################################################################
# types.xml - This is the definitions-file for all the different     #
# Crossfire object types and their attributes.                       #
#                                                                    #
# The server code of the Crossfire game is always changing and       #
# evolving. From time to time, object-attributes change in purpose,  #
# or new ones are created.                                           #
# Therefore, it is important that an Editor is flexible and          #
# easy to "upgrade" to handle such new features. That's why the      #
# CFJavaEditor reads the type-definitions from this xml file.        #
#                                                                    #
# If you encounter bugs, typos or missing entries in the LATEST      #
# VERSION of this file - Don't hesitate to improve it, contact me    #
# and eventually send the improved file to me: <red.blaze@gmx.net>.  #
# I will put it into the "official version" of the CFJavaEditor      #
# and all fellow Crossfire-Map-Makers can benefit from your work!    #
#                                                                    #
# IMPORTANT: Make a backup copy of this file before you start        #
# to modify it!                                                      #
#                                                                    #
# New types must be inserted maintaining the alphabetical order.     #
#                                                                    #
# about the 'type' elements:                                         #
#                                                                    #
# <type number="15" name="Type Name">                                #
# <import_type name="Type Name" />   import attributes of this type  #
# <required>                                                         #
#    list of required attributes to identifying this type            #
# </required>                                                        #
# <ignore>                                                           #
#    list of attributes not to import from default_type              #
# </ignore>                                                          #
# <description><![CDATA[                                             #
#   Description of this type. ]]>                                    #
# </description>                                                     #
# <use><![CDATA[                                                     #
#   How to use this type. ]]>                                        #
# </use>                                                             #
# ... attributes ...                                                 #
# </type>                                                            #
#                                                                    #
# about the 'attribute' type: <attribute ... type="XXX" >            #
#                                                                    #
# bool         - This attribute can only be set to '1' or '0'        #
# int          - This attribute contains a decimal number            #
# float        - This attr. contains a floating point number         #
# string       - This attribute contains a string                    #
# text         - This attribute contains a text ("text" can have     #
#                linebreaks, unlike "string")                        #
# fixed        - This attribute is always set to a fixed 'value'     #
#                (There is no user-input for this attribute)         #
# spell        - This attribute contains a spell. The mapmaker can   #
#                choose spells from a combo box.                     #
# nz_spell     - works just like 'spell', except that the            #
#                spell-value zero is always interpreted as <none>,   #
#                never as "magic bullet"                             #
# bool_special - Like bool, but with customized true/false values    #
# treasurelist - CF treasure list (see "treasures" file)             #
# list_LISTNAME       - list, must be defined as a <list> element    #
# bitmask_BITMASKNAME - bitmask, must be defined as a <bitmask>      #
#                       element                                      #
#                                                                    #
# Created by Andreas Vogl.                                           #
######################################################################
-->
<!DOCTYPE types [
  <!ELEMENT types ((bitmask | list | ignore_list)*, default_type, ignore_list*, type+)>

  <!ELEMENT bitmask (entry*)>
  <!ATTLIST bitmask name CDATA #REQUIRED>

  <!ELEMENT list (entry*)>
  <!ATTLIST list name CDATA #REQUIRED>

  <!ELEMENT entry EMPTY>
  <!ATTLIST entry bit   CDATA #IMPLIED
                  value CDATA #IMPLIED
                  name  CDATA #REQUIRED>

  <!ELEMENT ignore_list (attribute* | EMPTY)>
  <!ATTLIST ignore_list name CDATA #REQUIRED>

  <!ELEMENT default_type (attribute*)>

  <!ELEMENT type (import_type?,required?,ignore?,description?,use?,(section | attribute)*)>
  <!ATTLIST type name   CDATA #REQUIRED
                 number CDATA #REQUIRED>

  <!ELEMENT description (#PCDATA)>
  <!ELEMENT use (#PCDATA)>

  <!ELEMENT import_type EMPTY>
  <!ATTLIST import_type name CDATA #REQUIRED>

  <!ELEMENT required (attribute+)>
  <!ELEMENT ignore (attribute*,ignore_list*)>

  <!ELEMENT section (attribute+)>
  <!ATTLIST section name CDATA #REQUIRED>

  <!ELEMENT attribute (#PCDATA)>
  <!ATTLIST attribute type       CDATA #IMPLIED
                      arch       CDATA #IMPLIED
                      arch_begin CDATA #IMPLIED
                      arch_end   CDATA #IMPLIED
                      editor     CDATA #IMPLIED
                      value      CDATA #IMPLIED
                      length     CDATA #IMPLIED
                      true       CDATA #IMPLIED
                      false      CDATA #IMPLIED>

  <!ENTITY move_on "
     <attribute arch='move_on' editor='movement type' type='movement_type'>
        Which movement types automatically (as opposed to manually) activate this object.
     </attribute>
  ">
  <!ENTITY move_off "
     <attribute arch='move_off' editor='movement type' type='movement_type'>
        Which movement types deactivate this object (e.g. button).
     </attribute>
  ">
  <!ENTITY move_type "
     <attribute arch='move_type' editor='movement type' type='movement_type'>
        Determines which kinds of movement this object can use (e.g. for monsters)
        or grants (e.g. for amulets).
     </attribute>
  ">
  <!ENTITY movement_types_terrain "
     <attribute arch='move_block' editor='blocked movement' type='movement_type'>
       Objects using these movement types cannot move over this space.
     </attribute>
     <attribute arch='move_allow' editor='allowed movement' type='movement_type'>
       Objects using these movement types are allowed to move over this space. Takes
       precedence over 'blocked movements'.
     </attribute>
     <attribute arch='move_slow' editor='slowed movement' type='movement_type'>
       The types of movement that should by slowed down by the 'slow movement penalty'.
     </attribute>
     <attribute arch='move_slow_penalty' editor='slow movement penalty' type='int'>
       If &lt;slow movement&gt; is set to a value greater zero, all
       creatures matching 'slow move' will be slower than normal on this spot.

       &lt;slow movement&gt; 1  - rough terrain
       &lt;slow movement&gt; 2  - very rough terrain
       ...
       &lt;slow movement&gt; 5  - default for deep swamp
       ...
       &lt;slow movement&gt; 7  - spider web (sticky as hell)
     </attribute>
  ">
  <!ENTITY speed_left "
     <attribute arch='speed_left' editor='speed left' type='float'>
        The speed left to the object. On every tick, if this value is higher
        than 0, the object acts/triggers/moves etc. and the value gets
        decremented by 1. Otherwise, it is incremented by &lt;speed&gt; on
        every tick.
     </attribute>
  ">
  <!ENTITY activate_on "
     <attribute arch='activate_on_push' editor='Activate on push' type='bool'>
       Whether the teleporter should only be activated on push.
     </attribute>
     <attribute arch='activate_on_release' editor='Activate on release' type='bool'>
       Whether the teleporter should only be activated on release.
     </attribute>
  ">

  <!ENTITY resistances_flesh_desc "
    Resistances on flesh items make them more durable against spellcraft
    of the appropriate kind. It also allows dragon players to eventually gain
    resistance by eating it. Usually resistance should only be set for flesh
    items in a monster's inventory.
  ">

  <!ENTITY resistances_flesh_section "
   <section name='resistance'>
     <attribute arch='resist_physical' editor='resist physical &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_magic' editor='resist magic &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_fire' editor='resist fire &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_electricity' editor='resist electricity &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_cold' editor='resist cold &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_confusion' editor='resist confusion &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_acid' editor='resist acid &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_drain' editor='resist draining &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_weaponmagic' editor='resist weaponmagic &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_ghosthit' editor='resist ghosthit &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_poison' editor='resist poison &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_slow' editor='resist slow &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_paralyze' editor='resist paralyze &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_fear' editor='resist fear &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_deplete' editor='resist depletion &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_death' editor='resist death-attack &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_chaos' editor='resist chaos &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
     <attribute arch='resist_blind' editor='resist blinding &#x25;' length='15' type='int'>
       &resistances_flesh_desc;
     </attribute>
   </section>
  ">

  <!ENTITY resistances_basic "
   <section name='resistance'>
     <attribute arch='resist_physical' editor='resist physical &#x25;' length='15' type='int'/>
     <attribute arch='resist_magic' editor='resist magic &#x25;' length='15' type='int'/>
     <attribute arch='resist_fire' editor='resist fire &#x25;' length='15' type='int'/>
     <attribute arch='resist_electricity' editor='resist electricity &#x25;' length='15' type='int'/>
     <attribute arch='resist_cold' editor='resist cold &#x25;' length='15' type='int'/>
     <attribute arch='resist_confusion' editor='resist confusion &#x25;' length='15' type='int'/>
     <attribute arch='resist_acid' editor='resist acid &#x25;' length='15' type='int'/>
     <attribute arch='resist_drain' editor='resist draining &#x25;' length='15' type='int'/>
     <attribute arch='resist_weaponmagic' editor='resist weaponmagic &#x25;' length='15' type='int'/>
     <attribute arch='resist_ghosthit' editor='resist ghosthit &#x25;' length='15' type='int'/>
     <attribute arch='resist_poison' editor='resist poison &#x25;' length='15' type='int'/>
     <attribute arch='resist_slow' editor='resist slow &#x25;' length='15' type='int'/>
     <attribute arch='resist_paralyze' editor='resist paralyze &#x25;' length='15' type='int'/>
     <attribute arch='resist_fear' editor='resist fear &#x25;' length='15' type='int'/>
     <attribute arch='resist_deplete' editor='resist depletion &#x25;' length='15' type='int'/>
     <attribute arch='resist_death' editor='resist death-attack &#x25;' length='15' type='int'/>
     <attribute arch='resist_chaos' editor='resist chaos &#x25;' length='15' type='int'/>
     <attribute arch='resist_blind' editor='resist blinding &#x25;' length='15' type='int'/>
     <attribute arch='resist_holyword' editor='resist holy power &#x25;' length='15' type='int'/>
     <attribute arch='resist_godpower' editor='resist godpower &#x25;' length='15' type='int'/>
   </section>
  ">

   <!ENTITY player_stat_desc "
    The player's strentgh will rise/fall by the given value for permanent
    (of course there is an upper limit). Generally there shouldn't be stat
    potions granting more than one stat. Cursed potions will subtract the
    stats if positive.
   ">

   <!ENTITY player_res_desc "
    The player's resistance to physical will rise by this value in percent
    (range -100 till +100). The effect is only temporare, and it does NOT
    add on the values from the player's equipment.
    Cursed potions will make negative resistance.. very nasty in combat!
   ">

   <!ENTITY player_stat_resist_sections "
      <section name='stats'>
        <attribute arch='Str' editor='strength' type='int'>
          &player_stat_desc;
        </attribute>
        <attribute arch='Dex' editor='dexterity' type='int'>
          &player_stat_desc;
        </attribute>
        <attribute arch='Con' editor='constitution' type='int'>
          &player_stat_desc;
        </attribute>
        <attribute arch='Int' editor='intelligence' type='int'>
          &player_stat_desc;
        </attribute>
        <attribute arch='Pow' editor='power' type='int'>
          &player_stat_desc;
        </attribute>
        <attribute arch='Wis' editor='wisdom' type='int'>
          &player_stat_desc;
        </attribute>
        <attribute arch='Cha' editor='charisma' type='int'>
          &player_stat_desc;
        </attribute>
      </section>
      <section name='resistance'>
        <attribute arch='resist_physical' editor='resist physical &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_magic' editor='resist magic &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_fire' editor='resist fire &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_electricity' editor='resist electricity &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_cold' editor='resist cold &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_acid' editor='resist acid &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_confusion' editor='resist confusion &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_weaponmagic' editor='resist weaponmagic &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_ghosthit' editor='resist ghosthit &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_slow' editor='resist slow &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_fear' editor='resist fear &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_death' editor='resist death-attack &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_chaos' editor='resist chaos &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_blind' editor='resist blinding &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_holyword' editor='resist holy power &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_godpower' editor='resist godpower &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_paralyze' editor='resist paralyze &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_drain' editor='resist draining &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_deplete' editor='resist depletion &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
        <attribute arch='resist_poison' editor='resist poison &#x25;' length='15' type='int'>
          &player_res_desc;
        </attribute>
      </section>
   ">

]>

<types>

<!--###################### bitmask definitions ######################-->

<bitmask name="attacktype">
  <entry bit="0" name="Physical" />
  <entry bit="1" name="Magical" />
  <entry bit="2" name="Fire" />
  <entry bit="3" name="Electricity" />
  <entry bit="4" name="Cold" />
  <entry bit="5" name="Confusion" />
  <entry bit="6" name="Acid" />
  <entry bit="7" name="Drain" />
  <entry bit="8" name="Weaponmagic" />
  <entry bit="9" name="Ghosthit" />
  <entry bit="10" name="Poison" />
  <entry bit="11" name="Slow" />
  <entry bit="12" name="Paralyze" />
  <entry bit="13" name="Turn Undead" />
  <entry bit="14" name="Fear" />
  <entry bit="15" name="Cancellation" />
  <entry bit="16" name="Depletion" />
  <entry bit="17" name="Death" />
  <entry bit="18" name="Chaos" />
  <entry bit="19" name="Counterspell" />
  <entry bit="20" name="God Power" />
  <entry bit="21" name="Holy Power" />
  <entry bit="22" name="Blinding" />
</bitmask>

<bitmask name="material">
  <entry bit="0" name="Paper" />
  <entry bit="1" name="Iron" />
  <entry bit="2" name="Glass" />
  <entry bit="3" name="Leather" />
  <entry bit="4" name="Wood" />
  <entry bit="5" name="Organics" />
  <entry bit="6" name="Stone" />
  <entry bit="7" name="Cloth" />
  <entry bit="8" name="Adamantite" />
  <entry bit="9" name="Liquid" />
  <entry bit="10" name="Soft Metal" />
  <entry bit="11" name="Bone" />
  <entry bit="12" name="Ice" />
  <entry bit="13" name="(supress name on display)" />

</bitmask>

<bitmask name="spellpath">
  <entry bit="0" name="Protection" />
  <entry bit="1" name="Fire" />
  <entry bit="2" name="Frost" />
  <entry bit="3" name="Electricity" />
  <entry bit="4" name="Missiles" />
  <entry bit="5" name="Self" />
  <entry bit="6" name="Summoning" />
  <entry bit="7" name="Abjuration" />
  <entry bit="8" name="Restoration" />
  <entry bit="9" name="Detonation" />
  <entry bit="10" name="Mind" />
  <entry bit="11" name="Creation" />
  <entry bit="12" name="Teleportation" />
  <entry bit="13" name="Information" />
  <entry bit="14" name="Transmutation" />
  <entry bit="15" name="Transferrence" />
  <entry bit="16" name="Turning" />
  <entry bit="17" name="Wounding" />
  <entry bit="18" name="Death" />
  <entry bit="19" name="Light" />
</bitmask>

<bitmask name="will_apply">
  <entry bit="0" name="Apply Handles" />
  <entry bit="1" name="Open Chests" />
  <entry bit="2" name="Break Walls" />
  <entry bit="3" name="Open Doors" />
</bitmask>

<bitmask name="pick_up">
  <entry bit="0" name="Nothing" />
  <entry bit="1" name="Wealth" />
  <entry bit="2" name="Food" />
  <entry bit="3" name="Weapons" />
  <entry bit="4" name="Armour" />
  <entry bit="5" name="Inverse" />
  <entry bit="6" name="All" />
</bitmask>

<bitmask name="movement_type">
  <entry bit="0" name="Walk" />
  <entry bit="1" name="Fly Low" />
  <entry bit="2" name="Fly High" />
  <entry bit="3" name="Swim" />
  <entry bit="4" name="Boat" />
  <entry bit="16" name="Other" />
</bitmask>

<!--###################### list definitions ######################-->

<list name="direction">
  <entry value="0" name="&lt;none&gt;" />
  <entry value="1" name="north" />
  <entry value="2" name="northeast" />
  <entry value="3" name="east" />
  <entry value="4" name="southeast" />
  <entry value="5" name="south" />
  <entry value="6" name="southwest" />
  <entry value="7" name="west" />
  <entry value="8" name="northwest" />
</list>

<list name="mood">
  <entry value="0" name="furious" />
  <entry value="1" name="angry" />
  <entry value="2" name="calm" />
  <entry value="3" name="sleep" />
  <entry value="4" name="charm" />
</list>

<list name="potion_effect">
  <entry value="0" name="&lt;none&gt;" />
  <entry value="65536" name="life restoration" />
  <entry value="1048576" name="improvement" />
</list>

<list name="weapon_type">
  <entry value="0" name="&lt;unknown&gt;" />
  <entry value="1" name="sword" />
  <entry value="2" name="arrows" />
  <entry value="3" name="axe" />
  <entry value="4" name="katana" />
  <entry value="5" name="knife, dagger" />
  <entry value="6" name="whip, chain" />
  <entry value="7" name="hammer, flail" />
  <entry value="8" name="club, stick" />
</list>

<list name="skill_type">
  <entry value="1" name="lockpicking" />
  <entry value="2" name="hiding" />
  <entry value="3" name="smithery" />
  <entry value="4" name="bowyer" />
  <entry value="5" name="jeweler" />
  <entry value="6" name="alchemy" />
  <entry value="7" name="stealing" />
  <entry value="8" name="literacy" />
  <entry value="9" name="bargaining" />
  <entry value="10" name="jumping" />
  <entry value="11" name="detect magic" />
  <entry value="12" name="oratory" />
  <entry value="13" name="singing" />
  <entry value="14" name="detect curse" />
  <entry value="15" name="find traps" />
  <entry value="16" name="mediatation" />
  <entry value="17" name="punching" />
  <entry value="18" name="flame touch" />
  <entry value="19" name="karate" />
  <entry value="20" name="climbing" />
  <entry value="21" name="woodsman" />
  <entry value="22" name="inscription" />
  <entry value="23" name="one handed weapons" />
  <entry value="24" name="missile weapons" />
  <entry value="25" name="throwing" />
  <entry value="26" name="use magic item" />
  <entry value="27" name="disarm traps" />
  <entry value="28" name="set traps" />
  <entry value="29" name="thaumaturgy" />
  <entry value="30" name="praying" />
  <entry value="31" name="clawing" />
  <entry value="32" name="levitation" />
  <entry value="33" name="summoning" />
  <entry value="34" name="pyromancy" />
  <entry value="35" name="evocation" />
  <entry value="36" name="sorcery" />
  <entry value="37" name="two handed weapons" />
</list>

<list name="spell_type">
  <entry value="1" name="raise dead" />
  <entry value="2" name="rune" />
  <entry value="3" name="make mark" />
  <entry value="4" name="bolt" />
  <entry value="5" name="bullet" />
  <entry value="6" name="explosion" />
  <entry value="7" name="cone" />
  <entry value="8" name="bomb" />
  <entry value="9" name="wonder" />
  <entry value="10" name="smite" />
  <entry value="11" name="magic missile" />
  <entry value="12" name="summon golem" />
  <entry value="13" name="dimension door" />
  <entry value="14" name="magic mapping" />
  <entry value="15" name="magic wall" />
  <entry value="16" name="destruction" />
  <entry value="17" name="perceive self" />
  <entry value="18" name="word of recall" />
  <entry value="19" name="invisible" />
  <entry value="20" name="probe" />
  <entry value="21" name="healing" />
  <entry value="22" name="create food" />
  <entry value="23" name="earth to dust" />
  <entry value="24" name="change ability" />
  <entry value="25" name="bless" />
  <entry value="26" name="curse" />
  <entry value="27" name="summon monster" />
  <entry value="28" name="recharge" />
  <entry value="29" name="polymorph" />
  <entry value="30" name="alchemy" />
  <entry value="31" name="remove curse" />
  <entry value="32" name="identify" />
  <entry value="33" name="detection" />
  <entry value="34" name="mood change" />
  <entry value="35" name="moving ball" />
  <entry value="36" name="swarm" />
  <entry value="37" name="charge mana" />
  <entry value="38" name="dispel rune" />
  <entry value="39" name="create missile" />
  <entry value="40" name="consecrate" />
  <entry value="41" name="animate weapon" />
  <entry value="42" name="light" />
  <entry value="43" name="change map light" />
  <entry value="44" name="faery fire" />
  <entry value="45" name="disease" />
  <entry value="46" name="aura" />
  <entry value="47" name="town portal" />
</list>

<list name="event_type">
  <entry value="0" name="none" />
  <entry value="1" name="apply" />
  <entry value="2" name="attack" />
  <entry value="3" name="death" />
  <entry value="4" name="drop" />
  <entry value="5" name="pickup" />
  <entry value="6" name="say" />
  <entry value="7" name="stop" />
  <entry value="8" name="time" />
  <entry value="9" name="throw" />
  <entry value="10" name="trigger" />
  <entry value="11" name="close" />
  <entry value="12" name="timer" />
  <entry value="28" name="move" />
  <entry value="41" name="drop_on" />
</list>

<list name="attack_movement_bits_0_3">
   <entry value="0" name="default" />
   <entry value="1" name="attack from distance" />
   <entry value="2" name="run away" />
   <entry value="3" name="hit and run" />
   <entry value="4" name="wait, then hit, then move" />
   <entry value="5" name="rush blindly" />
   <entry value="6" name="always run" />
   <entry value="7" name="attack from distance if hit" />
   <entry value="8" name="do not approach" />
</list>

<list name="attack_movement_bits_4_7">
   <entry value="0" name="none" />
   <entry value="16" name="pet" />
   <entry value="32" name="small circle" />
   <entry value="48" name="large circle" />
   <entry value="64" name="small horizontal" />
   <entry value="80" name="large horizontal" />
   <entry value="96" name="random direction" />
   <entry value="112" name="random movement" />
   <entry value="128" name="small vertical" />
   <entry value="144" name="large vertical" />
</list>

<!--###################### default attributes ######################-->

<!--
  The attributes of the default_type get added to all other types by default.
  Every type can have an 'ignore' element however, which is used to specify
  default attributes *not* to inherit.
  -->
<default_type>
  <attribute arch="name" editor="name" type="string">
    This is the name of the object, displayed to the player.
  </attribute>
  <attribute arch="name_pl" editor="plural name" type="string">
    This is the plural name of the object. A plural name must be set for
    all items that can be picked up and collected by the player.
  </attribute>
  <attribute arch="title" editor="title" type="string">
    This is the object's title. Once an object is identified the title is
    attached to the name. Typical titles are "of Mostrai", "of xray vision" etc.
  </attribute>
  <attribute arch="face" editor="image" type="string">
    The image-name defines what image is displayed for this object in-game.
  </attribute>
  <attribute arch="nrof" editor="number" type="int">
    This value determines the number of objects in one stack (for example:
    100 goldcoins =&gt; "number = 100"). You should set this at least to one, for
    any pickable object - otherwise it won't be mergeable into a stack.
  </attribute>
  <attribute arch="weight" editor="weight" type="int">
    This value defines the object's weight in grams (1000g is 1kg). Objects with
    zero weight are not pickable for players. Still, set the "non-pickable"-flag
    for explicitly non-pickable objects (hey, this is opensource.. you
    never know ;) ).
  </attribute>
  <attribute arch="value" editor="value" type="int">
    Determines the value of the object, in units of silver coins (one
    platinum coin == 50 silver coins). Value for buying/selling will be
    further modified by various factors. Hence, testing values in-game is
    usually inevitable.
  </attribute>
  <attribute arch="glow_radius" editor="glow radius" type="int">
    If &lt;glow radius&gt; is set to a value greater zero, the object
    appears lit up on dark maps. &lt;glow radius&gt; can be a value
    between 0 and 4, the higher, the more light does the object emit.
  </attribute>
  <attribute arch="material" editor="material" type="bitmask_material">
    This bitmask-value informs the player of which material(s) the
    object consists. Material does also affect how likely the object
    can be destroyed by hazardous spell-effects.
  </attribute>
  <attribute arch="no_pick" editor="non-pickable" type="bool">
    If set, the object cannot be picked up (Neither by players nor monsters).
  </attribute>
  <attribute arch="invisible" editor="invisible" type="bool">
    Generally makes the object invisible. Depending on the object-type,
    some can be made visible by the show_invisible spell. If in doubt, test it.
    Putting an invisible object under the floor always prevents it from being
    shown.
  </attribute>